// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for Footer documents */
interface FooterDocumentData {
    /**
     * Internal Links field in *Footer*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.internalLinks[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    internalLinks: prismicT.GroupField<Simplify<FooterDocumentDataInternalLinksItem>>;
    /**
     * Social Links field in *Footer*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.social_links[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    social_links: prismicT.GroupField<Simplify<FooterDocumentDataSocialLinksItem>>;
    /**
     * Copyright field in *Footer*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.copyright
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    copyright: prismicT.RichTextField;
    /**
     * Slice Zone field in *Footer*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<FooterDocumentDataSlicesSlice>;
}
/**
 * Item in Footer → Internal Links
 *
 */
export interface FooterDocumentDataInternalLinksItem {
    /**
     * Link Label field in *Footer → Internal Links*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.internalLinks[].link_label
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    link_label: prismicT.RichTextField;
    /**
     * Link field in *Footer → Internal Links*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.internalLinks[].link
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    link: prismicT.LinkField;
}
/**
 * Item in Footer → Social Links
 *
 */
export interface FooterDocumentDataSocialLinksItem {
    /**
     * Social Link field in *Footer → Social Links*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.social_links[].social_link
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    social_link: prismicT.LinkField;
    /**
     * Social Icon field in *Footer → Social Links*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.social_links[].social_icon
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    social_icon: prismicT.ImageField<never>;
}
/**
 * Slice for *Footer → Slice Zone*
 *
 */
type FooterDocumentDataSlicesSlice = WufooFormSlice;
/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<FooterDocumentData>, "footer", Lang>;
/** Content for Homepage documents */
interface HomepageDocumentData {
    /**
     * Title field in *Homepage*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * Slice Zone field in *Homepage*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<HomepageDocumentDataSlicesSlice>;
}
/**
 * Slice for *Homepage → Slice Zone*
 *
 */
type HomepageDocumentDataSlicesSlice = AccordionSlice | HeroBannerSlice | SocialFeedFlickrSlice;
/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<HomepageDocumentData>, "homepage", Lang>;
/** Content for Landing page documents */
interface LandingPageDocumentData {
    /**
     * Slice Zone field in *Landing page*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: landing_page.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<LandingPageDocumentDataSlicesSlice>;
}
/**
 * Slice for *Landing page → Slice Zone*
 *
 */
type LandingPageDocumentDataSlicesSlice = HeroBannerSlice | AccordionSlice | SocialFeedFlickrSlice;
/**
 * Landing page document from Prismic
 *
 * - **API ID**: `landing_page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LandingPageDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<LandingPageDocumentData>, "landing_page", Lang>;
/** Content for Menu documents */
interface MenuDocumentData {
    /**
     * Logo field in *Menu*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: menu.logo
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    logo: prismicT.ImageField<never>;
    /**
     * Company name field in *Menu*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: menu.company_name
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    company_name: prismicT.KeyTextField;
    /**
     * Slice Zone field in *Menu*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: menu.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<MenuDocumentDataSlicesSlice>;
}
/**
 * Slice for *Menu → Slice Zone*
 *
 */
type MenuDocumentDataSlicesSlice = MenuSlice;
/**
 * Menu document from Prismic
 *
 * - **API ID**: `menu`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MenuDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<MenuDocumentData>, "menu", Lang>;
export type AllDocumentTypes = FooterDocument | HomepageDocument | LandingPageDocument | MenuDocument;
/**
 * Primary content in Accordion → Primary
 *
 */
interface AccordionSliceDefaultPrimary {
    /**
     * Title field in *Accordion → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: Accordion title
     * - **API ID Path**: accordion.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
}
/**
 * Item in Accordion → Items
 *
 */
export interface AccordionSliceDefaultItem {
    /**
     * Title field in *Accordion → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: Dropdown title
     * - **API ID Path**: accordion.items[].title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.RichTextField;
    /**
     * Content field in *Accordion → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: Content
     * - **API ID Path**: accordion.items[].content
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    content: prismicT.RichTextField;
}
/**
 * Default variation for Accordion Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Accordion`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type AccordionSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<AccordionSliceDefaultPrimary>, Simplify<AccordionSliceDefaultItem>>;
/**
 * Slice variation for *Accordion*
 *
 */
type AccordionSliceVariation = AccordionSliceDefault;
/**
 * Accordion Shared Slice
 *
 * - **API ID**: `accordion`
 * - **Description**: `Accordion`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type AccordionSlice = prismicT.SharedSlice<"accordion", AccordionSliceVariation>;
/**
 * Primary content in HeroBanner → Primary
 *
 */
interface HeroBannerSliceDefaultPrimary {
    /**
     * Title Top line field in *HeroBanner → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: Top line content
     * - **API ID Path**: hero_banner.primary.title_top_line
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title_top_line: prismicT.TitleField;
    /**
     * Title Bottom Line field in *HeroBanner → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: Bottom line content
     * - **API ID Path**: hero_banner.primary.title_bottom_line
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title_bottom_line: prismicT.TitleField;
    /**
     * Description field in *HeroBanner → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A nice description of your feature
     * - **API ID Path**: hero_banner.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
    /**
     * Image field in *HeroBanner → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: hero_banner.primary.image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
}
/**
 * Item in HeroBanner → Items
 *
 */
export interface HeroBannerSliceDefaultItem {
    /**
     * Cta Label field in *HeroBanner → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: hero_banner.items[].cta_label
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    cta_label: prismicT.KeyTextField;
    /**
     * Cta Link field in *HeroBanner → Items*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: hero_banner.items[].cta_link
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    cta_link: prismicT.LinkField;
    /**
     * Cta Type field in *HeroBanner → Items*
     *
     * - **Field Type**: Select
     * - **Placeholder**: Select button type
     * - **Default Value**: Primary
     * - **API ID Path**: hero_banner.items[].cta_type
     * - **Documentation**: https://prismic.io/docs/core-concepts/select
     *
     */
    cta_type: prismicT.SelectField<"Primary" | "Secondary", "filled">;
}
/**
 * Default variation for HeroBanner Slice
 *
 * - **API ID**: `default`
 * - **Description**: `HeroBanner`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeroBannerSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<HeroBannerSliceDefaultPrimary>, Simplify<HeroBannerSliceDefaultItem>>;
/**
 * Primary content in HeroBanner → Primary
 *
 */
interface HeroBannerSliceWithoutCtaPrimary {
    /**
     * Title Top line field in *HeroBanner → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: Top line content
     * - **API ID Path**: hero_banner.primary.title_top_line
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title_top_line: prismicT.TitleField;
    /**
     * Title Bottom Line field in *HeroBanner → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: Bottom line content
     * - **API ID Path**: hero_banner.primary.title_bottom_line
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title_bottom_line: prismicT.TitleField;
    /**
     * Description field in *HeroBanner → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A nice description of your feature
     * - **API ID Path**: hero_banner.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
    /**
     * Image field in *HeroBanner → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: hero_banner.primary.image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
}
/**
 * Without Cta variation for HeroBanner Slice
 *
 * - **API ID**: `withoutCta`
 * - **Description**: `HeroBanner`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeroBannerSliceWithoutCta = prismicT.SharedSliceVariation<"withoutCta", Simplify<HeroBannerSliceWithoutCtaPrimary>, never>;
/**
 * Slice variation for *HeroBanner*
 *
 */
type HeroBannerSliceVariation = HeroBannerSliceDefault | HeroBannerSliceWithoutCta;
/**
 * HeroBanner Shared Slice
 *
 * - **API ID**: `hero_banner`
 * - **Description**: `HeroBanner`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeroBannerSlice = prismicT.SharedSlice<"hero_banner", HeroBannerSliceVariation>;
/**
 * Primary content in Menu → Primary
 *
 */
interface MenuSliceDefaultPrimary {
    /**
     * Label field in *Menu → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: menu.primary.label
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    label: prismicT.RichTextField;
    /**
     * Link field in *Menu → Primary*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: menu.primary.link
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    link: prismicT.LinkField;
}
/**
 * Default variation for Menu Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Menu`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type MenuSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<MenuSliceDefaultPrimary>, never>;
/**
 * Primary content in Menu → Primary
 *
 */
interface MenuSliceDropdownPrimary {
    /**
     * Dropdown label field in *Menu → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: menu.primary.dropdown_label
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    dropdown_label: prismicT.RichTextField;
}
/**
 * Item in Menu → Items
 *
 */
export interface MenuSliceDropdownItem {
    /**
     * Second level label field in *Menu → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: menu.items[].second_level_label
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    second_level_label: prismicT.RichTextField;
    /**
     * Second level link field in *Menu → Items*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: menu.items[].second_level_link
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    second_level_link: prismicT.LinkField;
}
/**
 * Dropdown variation for Menu Slice
 *
 * - **API ID**: `dropdown`
 * - **Description**: `Menu`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type MenuSliceDropdown = prismicT.SharedSliceVariation<"dropdown", Simplify<MenuSliceDropdownPrimary>, Simplify<MenuSliceDropdownItem>>;
/**
 * Slice variation for *Menu*
 *
 */
type MenuSliceVariation = MenuSliceDefault | MenuSliceDropdown;
/**
 * Menu Shared Slice
 *
 * - **API ID**: `menu`
 * - **Description**: `Menu`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type MenuSlice = prismicT.SharedSlice<"menu", MenuSliceVariation>;
/**
 * Primary content in SocialFeedFlickr → Primary
 *
 */
interface SocialFeedFlickrSliceDefaultPrimary {
    /**
     * Title field in *SocialFeedFlickr → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: social_feed_flickr.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.RichTextField;
    /**
     * Social Link Label field in *SocialFeedFlickr → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: social_feed_flickr.primary.social_link_label
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    social_link_label: prismicT.KeyTextField;
    /**
     * Social Link Url field in *SocialFeedFlickr → Primary*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: social_feed_flickr.primary.social_link_url
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    social_link_url: prismicT.LinkField;
    /**
     * Number Of Posts field in *SocialFeedFlickr → Primary*
     *
     * - **Field Type**: Number
     * - **Placeholder**: Number Of Posts to display
     * - **API ID Path**: social_feed_flickr.primary.number_of_posts
     * - **Documentation**: https://prismic.io/docs/core-concepts/number
     *
     */
    number_of_posts: prismicT.NumberField;
}
/**
 * Default variation for SocialFeedFlickr Slice
 *
 * - **API ID**: `default`
 * - **Description**: `SocialFeedFlickr`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type SocialFeedFlickrSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<SocialFeedFlickrSliceDefaultPrimary>, never>;
/**
 * Slice variation for *SocialFeedFlickr*
 *
 */
type SocialFeedFlickrSliceVariation = SocialFeedFlickrSliceDefault;
/**
 * SocialFeedFlickr Shared Slice
 *
 * - **API ID**: `social_feed_flickr`
 * - **Description**: `SocialFeedFlickr`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type SocialFeedFlickrSlice = prismicT.SharedSlice<"social_feed_flickr", SocialFeedFlickrSliceVariation>;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { FooterDocumentData, FooterDocumentDataInternalLinksItem, FooterDocumentDataSocialLinksItem, FooterDocumentDataSlicesSlice, FooterDocument, HomepageDocumentData, HomepageDocumentDataSlicesSlice, HomepageDocument, LandingPageDocumentData, LandingPageDocumentDataSlicesSlice, LandingPageDocument, MenuDocumentData, MenuDocumentDataSlicesSlice, MenuDocument, AllDocumentTypes, AccordionSliceDefaultPrimary, AccordionSliceDefaultItem, AccordionSliceDefault, AccordionSliceVariation, AccordionSlice, HeroBannerSliceDefaultPrimary, HeroBannerSliceDefaultItem, HeroBannerSliceDefault, HeroBannerSliceWithoutCtaPrimary, HeroBannerSliceWithoutCta, HeroBannerSliceVariation, HeroBannerSlice, MenuSliceDefaultPrimary, MenuSliceDefault, MenuSliceDropdownPrimary, MenuSliceDropdownItem, MenuSliceDropdown, MenuSliceVariation, MenuSlice, SocialFeedFlickrSliceDefaultPrimary, SocialFeedFlickrSliceDefault, SocialFeedFlickrSliceVariation, SocialFeedFlickrSlice };
    }
}
