// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for Homepage documents */
type HomepageDocumentData = Record<string, never>;
/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<HomepageDocumentData>, "homepage", Lang>;
/** Content for Landing page documents */
type LandingPageDocumentData = Record<string, never>;
/**
 * Landing page document from Prismic
 *
 * - **API ID**: `landing_page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LandingPageDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<LandingPageDocumentData>, "landing_page", Lang>;
/** Content for Menu documents */
type MenuDocumentData = Record<string, never>;
/**
 * Menu document from Prismic
 *
 * - **API ID**: `menu`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MenuDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<MenuDocumentData>, "menu", Lang>;
export type AllDocumentTypes = HomepageDocument | LandingPageDocument | MenuDocument;
/**
 * Primary content in Menu → Primary
 *
 */
interface MenuSliceDefaultPrimary {
    /**
     * Company name field in *Menu → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: menu.primary.company_name
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    company_name: prismicT.KeyTextField;
    /**
     * Logo field in *Menu → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: menu.primary.logo
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    logo: prismicT.ImageField<never>;
    /**
     * Label field in *Menu → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: menu.primary.label
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    label: prismicT.RichTextField;
    /**
     * Link field in *Menu → Primary*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: menu.primary.link
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    link: prismicT.LinkField;
}
/**
 * Default variation for Menu Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Menu`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type MenuSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<MenuSliceDefaultPrimary>, never>;
/**
 * Primary content in Menu → Primary
 *
 */
interface MenuSliceDropdownPrimary {
    /**
     * Company name field in *Menu → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: menu.primary.company_name
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    company_name: prismicT.KeyTextField;
    /**
     * Logo field in *Menu → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: menu.primary.logo
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    logo: prismicT.ImageField<never>;
    /**
     * Dropdown label field in *Menu → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: menu.primary.dropdown_label
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    dropdown_label: prismicT.RichTextField;
}
/**
 * Item in Menu → Items
 *
 */
export interface MenuSliceDropdownItem {
    /**
     * Second level label field in *Menu → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: menu.items[].second_level_label
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    second_level_label: prismicT.RichTextField;
    /**
     * Second level link field in *Menu → Items*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: menu.items[].second_level_link
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    second_level_link: prismicT.LinkField;
}
/**
 * Dropdown variation for Menu Slice
 *
 * - **API ID**: `dropdown`
 * - **Description**: `Menu`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type MenuSliceDropdown = prismicT.SharedSliceVariation<"dropdown", Simplify<MenuSliceDropdownPrimary>, Simplify<MenuSliceDropdownItem>>;
/**
 * Slice variation for *Menu*
 *
 */
type MenuSliceVariation = MenuSliceDefault | MenuSliceDropdown;
/**
 * Menu Shared Slice
 *
 * - **API ID**: `menu`
 * - **Description**: `Menu`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type MenuSlice = prismicT.SharedSlice<"menu", MenuSliceVariation>;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { HomepageDocumentData, HomepageDocument, LandingPageDocumentData, LandingPageDocument, MenuDocumentData, MenuDocument, AllDocumentTypes, MenuSliceDefaultPrimary, MenuSliceDefault, MenuSliceDropdownPrimary, MenuSliceDropdownItem, MenuSliceDropdown, MenuSliceVariation, MenuSlice };
    }
}
