// Code generated by Slice Machine. DO NOT EDIT.

import HeroBanner from './HeroBanner';
import Menu from './Menu';

export {
	HeroBanner,
	Menu,
};

export const components = {
	hero_banner: HeroBanner,
	menu: Menu,
};
