// Code generated by Slice Machine. DO NOT EDIT.

import Accordion from './Accordion';
import Features from './Features';
import HeroBanner from './HeroBanner';
import Menu from './Menu';
import SocialFeedFlickr from './SocialFeedFlickr';

export {
	Accordion,
	Features,
	HeroBanner,
	Menu,
	SocialFeedFlickr,
};

export const components = {
	accordion: Accordion,
	features: Features,
	hero_banner: HeroBanner,
	menu: Menu,
	social_feed_flickr: SocialFeedFlickr,
};
