// Code generated by Slice Machine. DO NOT EDIT.

import Accordion from './Accordion';
import HeroBanner from './HeroBanner';
import Menu from './Menu';

export {
	Accordion,
	HeroBanner,
	Menu,
};

export const components = {
	accordion: Accordion,
	hero_banner: HeroBanner,
	menu: Menu,
};
